config/routes.rb
Rails.application.routes.draw do
  root "display#index"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :admin_users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in", to: "clearance/sessions#new", as: "sign_in"
  delete "/sign_out", to: "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up", to: "clearance/users#new", as: "sign_up"

  namespace :admin do
    resources :users
    resources :channels
    resources :messages
    resources :attachments
    resources :admin_users

    root to: "users#index"
  end

  get "search", to: "search#index"

  get ":channel_id", to: "display#show", as: :channel
  get ":channel_id/:date", to: "display#by_date", as: :channel_date
end

app/models/user.rb
class User < ApplicationRecord
  validates :slack_user, :display_name, presence: true
  validates :slack_user, :display_name, uniqueness: true

  has_many :messages, -> { order(posted_at: :asc) }
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def default_sorting_attribute
      :display_name
    end

    def default_sorting_direction
      :asc
    end
  end
end

app/views/users/_form.html.haml
.form-control.w-full
  = form.label :email, class: 'label label-text'
  = form.text_field :email, type: 'email', placeholder: t("helpers.label.password.email"), class: 'input input-bordered w-full'
.form-control.w-full
  = form.label :password, class: 'label label-text'
  = form.password_field :password, placeholder: t("helpers.label.user.password"), class: 'input input-bordered w-full'

app/views/users/new.html.haml
#clearance.sign-up
  %h1.text-2xl.pb-3= t(".title")
  = form_for @user do |form|
    = render partial: '/users/form', object: form
    .form-control
      = form.submit(t("helpers.submit.user.create"), class: 'btn w-full my-6')
    .other-links
      = link_to t(".sign_in"), sign_in_path